import {
  cta,
  divider,
  eyebrow,
  heading,
  infoBlock,
  note,
  paragraph,
  statusBadge,
  stepList,
  urlFallback,
} from '../design.js';
import { dashboardUrl } from '../urls.js';
import type { EmailTemplateDef } from '../types.js';
import { DEFAULT_REASON } from '../types.js';

export const accountTemplates: EmailTemplateDef[] = [
  {
    name: 'account.welcome',
    category: 'account',
    subject: 'Welcome to SEAI',
    preheader: 'Your SEAI account is ready — here is what happens next.',
    reason: DEFAULT_REASON,
    trigger: 'Customer account created (POST /api/auth/sign-up).',
    required: ['customer_name', 'email'],
    optional: ['dashboard_url'],
    wired: true,
    build: (ctx) => [
      eyebrow('Account created'),
      heading(`Welcome to SEAI${ctx.customer_name ? `, ${ctx.customer_name}` : ''}`),
      paragraph('Your SEAI account is active. This is the single place where you manage your website, request changes, and keep maintenance running.'),
      infoBlock('Account', [
        { label: 'Name', value: ctx.customer_name },
        { label: 'Email', value: ctx.email },
        { label: 'Dashboard', value: dashboardUrl(), href: dashboardUrl() },
      ]),
      paragraph('What happens next:'),
      stepList([
        'Confirm the email address we sent to you so account alerts always reach you.',
        'Send us your website details — pages, sections, content, and anything you already have.',
        'SEAI builds your website, sends you a preview, then publishes it on your domain.',
        'After launch you can request changes and add maintenance from the dashboard at any time.',
      ]),
      cta('Open SEAI Dashboard', dashboardUrl()),
      note('Nothing is charged by this email. Any payment is confirmed separately by SEAI.'),
    ],
  },
  {
    name: 'account.password_reset',
    category: 'account',
    subject: 'Reset your SEAI password',
    preheader: 'A secure, single-use link to choose a new SEAI password.',
    reason: DEFAULT_REASON,
    trigger: 'POST /api/auth/forgot-password for an existing account.',
    required: ['reset_url', 'email'],
    optional: ['expires_in_hours'],
    wired: true,
    build: (ctx) => [
      eyebrow('Account security'),
      heading('Reset your SEAI password'),
      paragraph(
        `A password reset was requested for ${ctx.email || 'your SEAI account'}. Use the link below to choose a new password.`,
      ),
      infoBlock('Reset link', [
        { label: 'Expires in', value: `${ctx.expires_in_hours || '1'} hour` },
        { label: 'Use', value: 'Single use — the link stops working after you set a new password' },
      ]),
      cta('Reset Password', ctx.reset_url),
      urlFallback(ctx.reset_url),
      divider(),
      statusBadge('Security notice', 'warning'),
      paragraph('If you did not request this, ignore this email. Your password does not change until you complete a reset, and no one can use the link without it.'),
      note(`If you did request this and nothing happens, contact SEAI at ${ctx.support_email} and we will help.`),
    ],
  },
  {
    name: 'account.password_changed',
    category: 'account',
    subject: 'Your SEAI password was changed',
    preheader: 'A security notice with the exact time your SEAI password changed.',
    reason: DEFAULT_REASON,
    trigger: 'POST /api/auth/reset-password completed successfully.',
    required: ['changed_at'],
    optional: ['email', 'dashboard_url'],
    wired: true,
    build: (ctx) => [
      eyebrow('Account security'),
      heading('Your password was changed'),
      paragraph('Your SEAI password has just been updated. Use it the next time you sign in to the dashboard.'),
      infoBlock('Change details', [
        { label: 'Changed at', value: ctx.changed_at },
        { label: 'Account', value: ctx.email },
      ]),
      divider(),
      statusBadge('Did not do this?', 'critical'),
      paragraph(
        'If you did not change your password, reset it immediately from the sign-in page and contact SEAI so we can secure your account.',
      ),
      cta('Open SEAI Dashboard', dashboardUrl()),
      note('SEAI never asks for your password by email, and will never send you one.'),
    ],
  },
  {
    name: 'account.new_sign_in_alert',
    category: 'account',
    subject: 'New sign-in to your SEAI account',
    preheader: 'A security notice for a new SEAI sign-in.',
    reason: DEFAULT_REASON,
    trigger: 'Reserved: no sign-in event store exists yet, so nothing emits this today.',
    required: ['changed_at', 'alert_summary'],
    optional: ['email'],
    wired: false,
    build: (ctx) => [
      eyebrow('Account security'),
      heading('A new sign-in to your SEAI account'),
      paragraph('SEAI recorded a sign-in that we have not seen before. If this was you, no action is needed.'),
      infoBlock('Sign-in', [
        { label: 'When', value: ctx.changed_at },
        { label: 'Details', value: ctx.alert_summary },
        { label: 'Account', value: ctx.email },
      ]),
      statusBadge('Not you?', 'critical'),
      paragraph('Reset your password immediately and contact SEAI so we can secure your account.'),
      cta('Open SEAI Dashboard', dashboardUrl()),
    ],
  },
];
