import { cta, heading, infoBlock, note, paragraph, statusBadge } from '../design.js';
import { maintenanceUrl } from '../urls.js';
import type { EmailTemplateDef } from '../types.js';
import { DEFAULT_REASON } from '../types.js';

export const maintenanceTemplates: EmailTemplateDef[] = [
  {
    name: 'maintenance.payment_required',
    category: 'maintenance',
    subject: 'Activate your SEAI maintenance',
    preheader: 'Complete payment to keep your site running.',
    reason: DEFAULT_REASON,
    trigger: 'Maintenance subscription created or reset to pending payment (no payment provider call).',
    required: ['plan_name', 'maintenance_price', 'status'],
    optional: ['maintenance_covers', 'billing_interval', 'customer_name'],
    wired: true,
    build: (ctx) => [
      statusBadge('Maintenance', 'warning'),
      heading('Keep your website running.'),
      paragraph('Complete your payment to activate your plan.'),
      infoBlock(null, [
        { label: 'Plan', value: ctx.plan_name },
        { label: 'Price', value: `${ctx.maintenance_price} / ${ctx.billing_interval}` },
      ]),
      cta('Activate maintenance', maintenanceUrl()),
      note('Questions? Reply to this email.'),
    ],
  },
  {
    name: 'maintenance.activated',
    category: 'maintenance',
    subject: 'SEAI maintenance is now active',
    preheader: 'Your plan is active.',
    reason: DEFAULT_REASON,
    trigger: 'Authoritative state change: maintenance subscription status becomes active.',
    required: ['plan_name', 'maintenance_price', 'activated_at', 'status'],
    optional: ['maintenance_covers', 'billing_interval', 'next_billing_date', 'website_name', 'domain'],
    wired: true,
    build: (ctx) => [
      statusBadge('Active', 'positive'),
      heading('Your maintenance is active.'),
      paragraph(
        ctx.website_name
          ? `We're looking after ${ctx.website_name} from here.`
          : "We're looking after your website from here.",
      ),
      infoBlock(null, [
        { label: 'Plan', value: ctx.plan_name },
        { label: 'Price', value: `${ctx.maintenance_price} / ${ctx.billing_interval}` },
        { label: 'Started', value: ctx.activated_at },
        ...(ctx.next_billing_date ? [{ label: 'Next billing', value: ctx.next_billing_date }] : []),
      ]),
      cta('Manage maintenance', maintenanceUrl()),
      note('Need a change? Request it from your dashboard any time.'),
    ],
  },
  {
    name: 'maintenance.payment_successful',
    category: 'maintenance',
    subject: 'SEAI maintenance payment received',
    preheader: 'Payment received.',
    reason: DEFAULT_REASON,
    trigger: 'Authoritative payment confirmation from the payment service.',
    required: ['amount', 'status'],
    optional: ['plan_name', 'payment_id', 'purchased_at', 'next_billing_date', 'billing_interval', 'maintenance_price'],
    wired: true,
    build: (ctx) => [
      statusBadge(ctx.status || 'Payment received', 'positive'),
      heading('Your maintenance payment is in.'),
      paragraph('Your plan continues without a break.'),
      infoBlock(null, [
        { label: 'Amount', value: ctx.amount },
        { label: 'Plan', value: ctx.plan_name },
        ...(ctx.next_billing_date ? [{ label: 'Next billing', value: ctx.next_billing_date }] : []),
      ]),
      cta('Manage maintenance', maintenanceUrl()),
    ],
  },
  {
    name: 'maintenance.payment_failed',
    category: 'maintenance',
    subject: 'Action needed for your SEAI maintenance',
    preheader: 'Your payment did not go through.',
    reason: DEFAULT_REASON,
    trigger: 'Authoritative payment failure from the payment service.',
    required: ['status'],
    optional: ['plan_name', 'amount', 'failure_reason', 'payment_id', 'maintenance_price', 'billing_interval'],
    wired: true,
    build: (ctx) => [
      statusBadge(ctx.status || 'Payment failed', 'critical'),
      heading("Your maintenance payment didn't go through."),
      paragraph('Update your payment to keep your plan running.'),
      infoBlock(null, [
        { label: 'Amount due', value: ctx.amount || ctx.maintenance_price },
        ...(ctx.failure_reason ? [{ label: 'Reason', value: ctx.failure_reason }] : []),
      ]),
      cta('Update payment', maintenanceUrl()),
    ],
  },
  {
    name: 'maintenance.renewing',
    category: 'maintenance',
    subject: 'Your SEAI maintenance renewal is coming up',
    preheader: 'Your plan renews soon.',
    reason: DEFAULT_REASON,
    trigger: 'Only when a real next_billing_date exists on the subscription record.',
    required: ['plan_name', 'maintenance_price', 'next_billing_date', 'billing_date'],
    optional: ['status', 'billing_interval', 'website_name'],
    wired: true,
    build: (ctx) => [
      statusBadge('Renewing soon', 'neutral'),
      heading('Your maintenance renews soon.'),
      infoBlock(null, [
        { label: 'Plan', value: ctx.plan_name },
        { label: 'Amount', value: `${ctx.maintenance_price} / ${ctx.billing_interval}` },
        { label: 'Date', value: ctx.billing_date || ctx.next_billing_date },
      ]),
      cta('Manage maintenance', maintenanceUrl()),
      note('No action needed if your payment details are up to date.'),
    ],
  },
  {
    name: 'maintenance.ended',
    category: 'maintenance',
    subject: 'Your SEAI maintenance has ended',
    preheader: 'Your plan has ended.',
    reason: DEFAULT_REASON,
    trigger: 'Authoritative state change: subscription status becomes cancelled or expired.',
    required: ['status'],
    optional: ['plan_name', 'maintenance_price', 'billing_date', 'website_name', 'domain'],
    wired: true,
    build: (ctx) => [
      statusBadge(ctx.status || 'Ended', 'neutral'),
      heading('Your maintenance has ended.'),
      paragraph('Your website stays online. Reactivate any time to pick up where you left off.'),
      infoBlock(null, [
        { label: 'Plan', value: ctx.plan_name },
        { label: 'Ended on', value: ctx.billing_date },
      ]),
      cta('Restart maintenance', maintenanceUrl()),
    ],
  },
  {
    name: 'maintenance.payment_reminder',
    category: 'maintenance',
    subject: 'Action needed for your SEAI maintenance',
    preheader: 'Your payment needs attention.',
    reason: DEFAULT_REASON,
    trigger: 'Reserved legacy template kept for compatibility; superseded by maintenance.payment_failed.',
    required: ['plan_name'],
    optional: ['maintenance_price', 'status', 'failure_reason', 'amount'],
    wired: false,
    build: (ctx) => [
      statusBadge('Action needed', 'warning'),
      heading('Your maintenance payment needs attention.'),
      paragraph('Update your payment to keep your plan running.'),
      infoBlock(null, [
        { label: 'Plan', value: ctx.plan_name },
        { label: 'Amount due', value: ctx.amount || ctx.maintenance_price },
      ]),
      cta('Update payment', maintenanceUrl()),
    ],
  },
];
