import { cta, eyebrow, heading, infoBlock, linkList, note, paragraph, statusBadge } from '../design.js';
import { dashboardUrl, maintenanceUrl } from '../urls.js';
import type { EmailTemplateDef } from '../types.js';
import { DEFAULT_REASON } from '../types.js';

const PAYMENT_SUPPORT = [
  'Check the amount and status shown above against your bank statement.',
  'Retry the payment from the SEAI dashboard — it takes a minute.',
  'If it keeps failing, reply to this email and we will sort it out with you.',
];

export const paymentTemplates: EmailTemplateDef[] = [
  {
    name: 'payment.successful',
    category: 'payment',
    subject: 'Your SEAI payment was successful',
    preheader: 'Payment confirmed by SEAI.',
    reason: DEFAULT_REASON,
    trigger: 'Authoritative payment.succeeded event from the payment service.',
    required: ['amount', 'status'],
    optional: ['order_id', 'payment_id', 'purchased_at', 'plan_name', 'currency', 'order_total', 'receipt_id'],
    wired: true,
    build: (ctx) => [
      statusBadge('Payment successful', 'positive'),
      eyebrow('Payment'),
      heading('We received your payment'),
      paragraph('SEAI confirms this payment is complete. Nothing further is needed from you.'),
      infoBlock('Payment', [
        { label: 'Amount', value: ctx.amount },
        { label: 'Description', value: ctx.plan_name },
        { label: 'Order ID', value: ctx.order_id },
        { label: 'Payment ID', value: ctx.payment_id },
        { label: 'Paid on', value: ctx.purchased_at },
        { label: 'Status', value: ctx.status || 'Successful' },
      ]),
      cta('Open SEAI Dashboard', dashboardUrl()),
      note('Questions about this payment? Reply to this email with the payment ID above.'),
    ],
  },
  {
    name: 'payment.failed',
    category: 'payment',
    subject: 'Your SEAI payment failed',
    preheader: 'We could not take your payment.',
    reason: DEFAULT_REASON,
    trigger: 'Authoritative payment.failed event from the payment service.',
    required: ['status'],
    optional: ['amount', 'failure_reason', 'order_id', 'payment_id', 'plan_name'],
    wired: true,
    build: (ctx) => [
      statusBadge('Payment failed', 'critical'),
      eyebrow('Payment'),
      heading('Your payment did not go through'),
      paragraph('The payment was declined, so nothing has been charged and your order is not confirmed yet.'),
      infoBlock('Payment', [
        { label: 'Amount', value: ctx.amount },
        { label: 'Order ID', value: ctx.order_id },
        { label: 'Attempt ID', value: ctx.payment_id },
        { label: 'Status', value: ctx.status || 'Failed' },
        ...(ctx.failure_reason ? [{ label: 'Reason', value: ctx.failure_reason }] : []),
      ]),
      paragraph('What to do now:'),
      infoBlock('Next steps', [{ label: 'Do', value: PAYMENT_SUPPORT.join(' ') }]),
      cta('Retry Payment in Dashboard', dashboardUrl()),
    ],
  },
  {
    name: 'payment.pending',
    category: 'payment',
    subject: 'Action required to complete your SEAI payment',
    preheader: 'Your payment is still waiting for confirmation.',
    reason: DEFAULT_REASON,
    trigger: 'Authoritative payment.pending / requires_action event from the payment service.',
    required: ['status'],
    optional: ['amount', 'failure_reason', 'order_id', 'payment_id', 'plan_name'],
    wired: true,
    build: (ctx) => [
      statusBadge('Payment pending', 'warning'),
      eyebrow('Action required'),
      heading('Finish your payment to continue'),
      paragraph(
        'Your payment has not been confirmed yet, so your order is on hold. It usually takes a moment for a bank transfer or method confirmation to settle.',
      ),
      infoBlock('Payment', [
        { label: 'Amount', value: ctx.amount },
        { label: 'Order ID', value: ctx.order_id },
        { label: 'Reference', value: ctx.payment_id },
        { label: 'Status', value: ctx.status || 'Pending' },
        ...(ctx.failure_reason ? [{ label: 'Note', value: ctx.failure_reason }] : []),
      ]),
      paragraph('What to do now:'),
      infoBlock('Next steps', [{ label: 'Do', value: PAYMENT_SUPPORT.join(' ') }]),
      cta('Complete Payment in Dashboard', dashboardUrl()),
      note('We will email you the moment the payment is confirmed. You do not need to pay twice.'),
    ],
  },
  {
    name: 'payment.refunded',
    category: 'payment',
    subject: 'Your SEAI refund has been issued',
    preheader: 'A refund was issued to your original payment method.',
    reason: DEFAULT_REASON,
    trigger: 'Authoritative refund.issued event from the payment service.',
    required: ['refund_amount', 'status'],
    optional: ['amount', 'order_id', 'payment_id', 'purchased_at', 'plan_name'],
    wired: true,
    build: (ctx) => [
      statusBadge('Refund issued', 'positive'),
      eyebrow('Refund'),
      heading('Your refund has been issued'),
      paragraph('The amount below was refunded to your original payment method. Most banks post it within 3–5 business days.'),
      infoBlock('Refund', [
        { label: 'Refunded', value: ctx.refund_amount },
        { label: 'Original payment', value: ctx.amount },
        { label: 'Order ID', value: ctx.order_id },
        { label: 'Payment ID', value: ctx.payment_id },
        { label: 'Issued on', value: ctx.purchased_at },
        { label: 'Status', value: ctx.status || 'Refunded' },
      ]),
      linkList([
        { label: 'Open SEAI Dashboard', href: dashboardUrl() },
        { label: 'Manage maintenance', href: maintenanceUrl() },
      ]),
      note('If the refund has not appeared after 5 business days, reply to this email with the order ID above.'),
    ],
  },
  {
    name: 'payment.receipt',
    category: 'payment',
    subject: 'Your SEAI payment receipt',
    preheader: 'Receipt for your SEAI payment.',
    reason: DEFAULT_REASON,
    trigger: 'Authoritative receipt request from the payment service or the SEAI dashboard.',
    required: ['amount', 'order_id', 'purchased_at', 'status'],
    optional: ['payment_id', 'receipt_id', 'plan_name', 'order_total', 'currency'],
    wired: true,
    build: (ctx) => [
      eyebrow('Receipt'),
      heading('Your SEAI payment receipt'),
      paragraph('This is your receipt for the payment below. Keep it for your records.'),
      infoBlock('Receipt', [
        { label: 'Receipt ID', value: ctx.receipt_id || ctx.order_id },
        { label: 'Order ID', value: ctx.order_id },
        { label: 'Payment ID', value: ctx.payment_id },
        { label: 'Amount paid', value: ctx.amount },
        { label: 'Description', value: ctx.plan_name },
        { label: 'Paid on', value: ctx.purchased_at },
        { label: 'Status', value: ctx.status },
      ]),
      cta('Open SEAI Dashboard', dashboardUrl()),
      note(`Questions about this receipt? Reply to this email and quote ${ctx.order_id}.`),
    ],
  },
];
